config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  root "application#root"
  get "/vote/:token", to: "vote#vote", as: :show_vote
  patch "/vote/:token", to: "vote#cast_vote", as: :cast_vote
  namespace :admin do
    resources :fixtures
    resources :entries
    resources :contests do
      get :send_votes, to: "contests#send_votes"
    end
    resources :contestants
    resources :votes
  end
end

app/models/contestant.rb
# frozen_string_literal: true

class Contestant < ApplicationRecord
  validates :name, :surname, :title, presence: true
  validates :name, uniqueness: { scope: %i[surname title] }
  has_many :entries, dependent: :destroy
  has_many :contests, through: :entries

  def full_name
    "#{surname} #{name}, #{title}"
  end
end

app/controllers/admin/contestants_controller.rb
# frozen_string_literal: true

class Admin::ContestantsController < ApplicationController
  before_action :authenticate_admin!
  expose :contestants, -> { Contestant.all }
  expose :contestant

  def index; end

  def show; end

  def new; end

  def edit; end

  def create
    respond_to do |format|
      if contestant.save
        format.html { redirect_to contestant, notice: 'Contestant was successfully created.' }
        format.json { render :show, status: :created, location: contestant }
      else
        format.html { render :new }
        format.json { render json: contestant.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if contestant.update(contestant_params)
        format.html { redirect_to contestant, notice: 'Contestant was successfully updated.' }
        format.json { render :show, status: :ok, location: contestant }
      else
        format.html { render :edit }
        format.json { render json: contestant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    contestant.destroy
    respond_to do |format|
      format.html { redirect_to contestants_url, notice: 'Contestant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def contestant_params
    params.require(:contestant).permit(
      :name,
      :surname,
      :title,
    )
  end
end

app/helpers/contestants_helper.rb
# frozen_string_literal: true

module ContestantsHelper
end

app/views/admin/contestants/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(contestant) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :surname
    = f.input :title

  .form-actions
    = f.button :submit

app/views/admin/contestants/edit.html.haml
%h1 Editing contestant

= render 'form'

= link_to 'Show', contestant
\|
= link_to 'Back', admin_contestants_path

app/views/admin/contestants/index.html.haml
%h1 Listing contestants

%table
  %thead
    %tr
      %th Imię
      %th Nazwisko
      %th Tytuł
      %th
      %th
      %th

  %tbody
    - contestants.each do |contestant|
      %tr
        %td= contestant.name
        %td= contestant.surname
        %td= contestant.title
        %td= link_to 'Show', admin_contestant_path(contestant)
        %td= link_to 'Edit', edit_admin_contestant_path(contestant)
        %td= link_to 'Destroy', admin_contestant_path(contestant), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Contestant', new_admin_contestant_path

app/views/admin/contestants/new.html.haml
%h1 New contestant

= render 'form'

= link_to 'Back', admin_contestants_path

app/views/admin/contestants/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_admin_contestant_path(contestant)
\|
= link_to 'Back', admin_contestants_path