config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  root "application#root"
  get "/vote/:token", to: "vote#vote", as: :show_vote
  patch "/vote/:token", to: "vote#cast_vote", as: :cast_vote
  namespace :admin do
    resources :fixtures
    resources :entries
    resources :contests do
      get :send_votes, to: "contests#send_votes"
    end
    resources :contestants
    resources :votes
  end
end

app/models/contest.rb
# frozen_string_literal: true

class Contest < ApplicationRecord
  include AASM

  validates :name, presence: true
  validates :name, uniqueness: true
  has_many :entries, dependent: :destroy
  has_many :contestants, through: :entries
  has_many :votes, dependent: :restrict_with_error

  aasm do
    state :inactive, initial: true
    state :active
    state :finished

    event :activate do
      transitions from: %i[inactive finished], to: :active, if: :no_other_contest_is_active?
    end

    event :finish do
      transitions from: :active, to: :finished
    end
  end

  def no_other_contest_is_active?
    self.class.active.count.zero?
  end
end

app/controllers/admin/contests_controller.rb
# frozen_string_literal: true

class Admin::ContestsController < ApplicationController
  before_action :authenticate_admin!
  expose :contests, -> { Contest.all }
  expose :contest

  def index; end

  def show; end

  def new; end

  def edit; end

  def create
    respond_to do |format|
      if contest.save
        format.html { redirect_to contest, notice: 'Contest was successfully created.' }
        format.json { render :show, status: :created, location: contest }
      else
        format.html { render :new }
        format.json { render json: contest.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if contest.update(contest_params)
        format.html { redirect_to contest, notice: 'Contest was successfully updated.' }
        format.json { render :show, status: :ok, location: contest }
      else
        format.html { render :edit }
        format.json { render json: contest.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    contest.destroy
    respond_to do |format|
      format.html { redirect_to contests_url, notice: 'Contest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def send_votes
    contest.votes.in_groups_of(100, false).each do |group|
      group.each do |vote|
        SendVotingMailJob.perform_later(vote: vote)
      end
      sleep 60
    end
    redirect_to contests_url, notice: "Successfully sent messages"
  end

  private

  def contest_params
    param.require(:contest).permit(
      :name,
      :expires_at,
    )
  end
end

app/helpers/contests_helper.rb
# frozen_string_literal: true

module ContestsHelper
end

app/views/admin/contests/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(contest, url: admin_contests_path) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :expires_at

  .form-actions
    = f.button :submit

app/views/admin/contests/edit.html.haml
%h1 Editing contest

= render 'form'

= link_to 'Show', admin_contest_path(contest)
\|
= link_to 'Back', admin_contests_path

app/views/admin/contests/index.html.haml
%h1 Listing contests

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th
      %th

  %tbody
    - contests.each do |contest|
      %tr
        %td= contest.name
        %td= link_to 'Send votes', admin_contest_send_votes_path(contest)
        %td= link_to 'Show', admin_contest_path(contest)
        %td= link_to 'Edit', edit_admin_contest_path(contest)
        %td= link_to 'Destroy', admin_contest_path(contest), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Contest', new_admin_contest_path

app/views/admin/contests/new.html.haml
%h1 New contest

= render 'form'

= link_to 'Back', admin_contests_path

app/views/admin/contests/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_admin_contest_path(contest)
\|
= link_to 'Back', admin_contests_path