config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  root "application#root"
  get "/vote/:token", to: "vote#vote", as: :show_vote
  patch "/vote/:token", to: "vote#cast_vote", as: :cast_vote
  namespace :admin do
    resources :fixtures
    resources :entries
    resources :contests do
      get :send_votes, to: "contests#send_votes"
    end
    resources :contestants
    resources :votes
  end
end

app/models/vote.rb
# frozen_string_literal: true

class Vote < ApplicationRecord
  has_secure_token
  validates :email, presence: true
  belongs_to :contest
  belongs_to :entry, optional: true
end

app/controllers/admin/votes_controller.rb
# frozen_string_literal: true

class Admin::VotesController < ApplicationController
  before_action :authenticate_admin!
  expose :votes, -> { Vote.all }
  expose :vote

  def index; end

  def show; end

  def new; end

  def edit; end

  def create
    respond_to do |format|
      if vote.save
        format.html { redirect_to vote, notice: 'Vote was successfully created.' }
        format.json { render :show, status: :created, location: vote }
      else
        format.html { render :new }
        format.json { render json: vote.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if vote.update(vote_params)
        format.html { redirect_to vote, notice: 'Vote was successfully updated.' }
        format.json { render :show, status: :ok, location: vote }
      else
        format.html { render :edit }
        format.json { render json: vote.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    vote.destroy
    respond_to do |format|
      format.html { redirect_to votes_url, notice: 'Vote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def vote_params
    params.require(:vote).permit(
      :contest_id,
      :contestant_id,
    )
  end
end

app/controllers/vote_controller.rb
# frozen_string_literal: true

class VoteController < ApplicationController
  expose(:user_vote) { Vote.find_by!(token: params[:token]) }
  expose(:contest) { user_vote.contest }
  expose(:entries) { contest.entries.includes([:contestant]) }

  def vote
    verify_token || return
  end

  def cast_vote
    verify_token || return
    if user_vote.update(vote_params)
      user_vote.update(cast: true)
      redirect_to root_path, notice: "Dziękujemy za oddanie głosu!"
    else
      render :vote, notice: "Coś poszło nie tak, spróbuj jeszcze raz."
    end
  end

  private

  def vote_params
    params.require(:vote).permit(
      :id,
      :entry_id
    )
  end

  def verify_token
    if params[:token] != user_vote.token || user_vote.cast
      redirect_to(root_path, alert: "Oddałeś już głos. Jeżeli tak nie jest to prosimy o kontakt z Samorządem Studenckim W-8") && return
    end

    true
  end
end

app/helpers/vote_helper.rb
# frozen_string_literal: true

module VoteHelper
end

app/helpers/votes_helper.rb
# frozen_string_literal: true

module VotesHelper
end

app/views/admin/votes/_form.html.haml
= form_for vote do |f|
  - if vote.errors.any?
    #error_explanation
      %h2= "#{pluralize(vote.errors.count, "error")} prohibited this vote from being saved:"
      %ul
        - vote.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/admin/votes/edit.html.haml
%h1 Editing vote

= render 'form'

= link_to 'Show', vote
\|
= link_to 'Back', votes_path

app/views/admin/votes/index.html.haml
%h1 Listing votes

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - votes.each do |vote|
      %tr
        %td= link_to 'Show', admin_vote_path(vote)
        %td= link_to 'Edit', edit_admin_vote_path(vote)
        %td= link_to 'Destroy', admin_vote_path(vote), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Vote', new_admin_vote_path

app/views/admin/votes/new.html.haml
%h1 New vote

= render 'form'

= link_to 'Back', votes_path

app/views/admin/votes/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_vote_path(vote)
\|
= link_to 'Back', votes_path