config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  root "application#root"
  get "/vote/:token", to: "vote#vote", as: :show_vote
  patch "/vote/:token", to: "vote#cast_vote", as: :cast_vote
  namespace :admin do
    resources :fixtures
    resources :entries
    resources :contests do
      get :send_votes, to: "contests#send_votes"
    end
    resources :contestants
    resources :votes
  end
end

app/models/entry.rb
# frozen_string_literal: true

class Entry < ApplicationRecord
  belongs_to :contest
  belongs_to :contestant
  validates :contestant_id, uniqueness: { scope: :contest_id }
  has_many :votes, dependent: :restrict_with_error

  def to_s
    contestant.full_name
  end
end

app/controllers/admin/entries_controller.rb
# frozen_string_literal: true

class Admin::EntriesController < ApplicationController
  before_action :authenticate_admin!
  expose :contestants, -> { Contestant.all }
  expose :contests, -> { Contest.active }
  expose :entries, -> { Entry.all }
  expose :entry

  def index; end

  def show; end

  def new; end

  def edit; end

  def create
    respond_to do |format|
      if entry.save
        format.html { redirect_to entry, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: entry }
      else
        format.html { render :new }
        format.json { render json: entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if entry.update(entry_params)
        format.html { redirect_to entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: entry }
      else
        format.html { render :edit }
        format.json { render json: entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def entry_params
    params.require(:entry).permit(
      :contestant_id,
      :contest_id
    )
  end
end

app/helpers/entries_helper.rb
# frozen_string_literal: true

module EntriesHelper
end

app/views/admin/entries/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(entry) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :contestant, collection: contestants
    = f.input :contest, collection: contests

  .form-actions
    = f.button :submit

app/views/admin/entries/edit.html.haml
%h1 Editing entry

= render 'form'

= link_to 'Show', entry
\|
= link_to 'Back', admin_entries_path

app/views/admin/entries/index.html.haml
%h1 Listing entries

%table
  %thead
    %tr
      %th Imię i nazwisko
      %th Konkurs
      %th
      %th
      %th

  %tbody
    - entries.each do |entry|
      %tr
        %td= "#{entry.contestant.name} #{entry.contestant.surname} #{entry.contestant.title}"
        %td= entry.contest.name
        %td= link_to 'Show', admin_entry_path(entry)
        %td= link_to 'Edit', edit_admin_entry_path(entry)
        %td= link_to 'Destroy', admin_entry_path(entry), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Entry', new_admin_entry_path

app/views/admin/entries/new.html.haml
%h1 New entry

= render 'form'

= link_to 'Back', admin_entries_path

app/views/admin/entries/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_admin_entry_path(entry)
\|
= link_to 'Back', admin_entries_path